name: Extract Boot Image Info and Upload

on:
  push:
    branches:
      - main

jobs:
  extract-boot-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3

      - name: Clone Android Image Kitchen
        run: git clone https://github.com/osm0sis/Android-Image-Kitchen.git

      - name: Extract Boot Image Info
        run: |
          cd Android-Image-Kitchen
          wget -O boot.img https://s3.ap-south-1.amazonaws.com/blob-ap-south-1-ukyez4/sara/be/bea5/bea54e18-cc6f-4049-9cc9-2455af366f1d.bin?response-content-disposition=attachment%3B%20filename%3D%22boot.img%22&response-content-type=&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=${{ secrets.AWS_CREDENTIALS }}&X-Amz-Date=${{ github.event.head_commit.timestamp }}&X-Amz-SignedHeaders=host&X-Amz-Expires=1800&X-Amz-Signature=${{ secrets.AWS_SIGNATURE }}
          python3 unpackimg.py boot.img

      - name: Upload Boot Image Info to Bashupload
        run: |
          cd Android-Image-Kitchen
          cat split_img/boot.img-zImage | gzip -c | curl -T - https://bashupload.com/$(date +%s)_boot_info.gz
