name: Extract Boot Image Info

on:
  push:
    branches:
      - main

jobs:
  extract_boot_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Boot Image
        run: |
          wget -O boot.img ${{ https://oshi.at/KHSs }}
          ls -lah boot.img

      - name: Install simg2img tool
        run: |
          sudo apt update
          sudo apt install -y android-tools-fsutils

      - name: Extract Boot Image Info
        run: |
          simg2img boot.img boot_raw.img
          file boot_raw.img
          strings -n 10 boot_raw.img

      - name: Upload Info to Bashupload
        run: |
          response=$(curl --silent --show-error --upload-file boot_raw.img https://bashupload.com)
          echo "Boot Image Info: https://bashupload.com$response"
