name: Unpack boot.img
on: [push]
jobs:
  unpack_boot_img:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 8
    - name: Download boot.img
      run: |
        wget https://s3.ap-south-1.amazonaws.com/blob-ap-south-1-ukyez4/sara/be/bea5/bea54e18-cc6f-4049-9cc9-2455af366f1d.bin?response-content-disposition=attachment%3B%20filename%3D%22boot.img%22&response-content-type=&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA4DM2EY46SOWUMUP4%2F20230410%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20230410T053748Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1800&X-Amz-Signature=7e1864fb7d5fb7ba68dee999d058cb606e3b19155eddef103ff5b863fc7c9eb1 -O boot.img
    - name: Install mkbootimg
      run: |
        sudo apt-get update
        sudo apt-get -y install git build-essential
        git clone https://github.com/xiaolu/mkbootimg_tools.git
        cd mkbootimg_tools
        make
        sudo cp mkboot bootimg_tools /usr/local/bin/
    - name: Unpack boot.img
      run: |
        mkdir unpacked_boot
        mkboot unpack boot.img unpacked_boot/
    - name: Upload unpacked files
      uses: actions/upload-artifact@v2
      with:
        name: unpacked-boot
        path: unpacked_boot
