name: Extract boot.img info and upload to bashupload

on:
  push:
    branches:
      - main

jobs:
  extract-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download boot.img and extract information
      run: |
        wget -qO- <https://s3.ap-south-1.amazonaws.com/blob-ap-south-1-ukyez4/sara/be/bea5/bea54e18-cc6f-4049-9cc9-2455af366f1d.bin?response-content-disposition=attachment%3B%20filename%3D%22boot.img%22&response-content-type=&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA4DM2EY46SOWUMUP4%2F20230409%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20230409T065553Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1800&X-Amz-Signature=ba42a476aa140f8280f553ba99bba3d3bfeddad2bb48fb9bcb528f3ee9812344 | strings > boot_info.txt

    - name: Upload boot info file to bashupload
      run: |
        upload_url=$(curl -s -X POST bashupload.com -H "Max-Downloads: 1" -H "Max-Days: 3" -H "Upload-Key: ${{ secrets.BASHUPLOAD_API_KEY }}" -T boot_info.txt)
        echo "Boot info file uploaded to: $upload_url"
