name: Extract Boot Image Info and Upload to Bashupload

on:
  push:
    branches: [ main ]

jobs:
  extract_and_upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y simg2img curl jq
        
    - name: Extract boot.img information
      run: |
        mkdir output
        curl -L https://oshi.at/KHSs -o boot.img
        simg2img boot.img output/boot.img.raw
        unpackbootimg -i output/boot.img.raw -o output/
        rm output/boot.img.raw
        
    - name: Upload boot image info to Bashupload
      run: |
        cd output
        zip -r boot_info.zip .
        curl -s -F "file=@boot_info.zip" https://bashupload.com/upload/hash
      env:
        BOOT_IMG_URL: ${{ env.BOOT_IMG_URL }}
